name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # This triggers the workflow when changes are pushed to the main branch
  workflow_dispatch:  # Allows you to trigger this workflow manually from GitHub Actions UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the latest code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js environment (only if you have build steps; remove if not needed)
      # This is optional and only necessary if you're using Node.js or npm to build the website.
      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '18'

      # Step 3: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Token used for authentication (provided automatically by GitHub Actions)
          publish_dir: ./  # The directory where your HTML files are located. For subdirectories, modify this path accordingly.

      # Optional: Add a step for any custom build processes (like minifying HTML, etc.)
      # - name: Build the site
      #   run: npm run build  # Adjust based on your build process
