name: Deploy GitHub Pages

# Trigger the workflow on push to main or on changes to the GitHub Pages files
on:
  push:
    branches:
      - main
    paths:
      - '**.html'   # Only trigger if HTML files change
      - '**.css'
      - '**.js'
      - README.md
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js to use GitHub Pages tools
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    # Install dependencies, if any (optional, remove if unnecessary)
    # Uncomment this if you have a package.json for building files
    # - name: Install dependencies
    #   run: npm install

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Root directory where your HTML content is
